# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='...', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.ImageField(default='images/events/empty.jpg', upload_to='images/events'),
        ),
    ]
